name: 'Fireblocks Solana Config Manager'
description:
  'Sets up Fireblocks and Solana configuration files for testing with automatic
  cleanup'
author: 'dchimento'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: shield
  color: orange

# Define your inputs here.
inputs:
  fireblocks-secret:
    description: 'Fireblocks secret key content (PEM format)'
    required: true
  fireblocks-api-key:
    description: 'Fireblocks API key'
    required: true
  fireblocks-vault:
    description: 'Fireblocks vault ID'
    required: false
    default: '0'
  solana-rpc-url:
    description: 'Solana RPC URL'
    required: false
    default: 'https://api.devnet.solana.com'

# Define your outputs here.
outputs:
  config-path:
    description: 'Path to the created configuration directory'

runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
