name: 'Fireblocks Solana Config Manager'
description:
  'Sets up Fireblocks and Solana configuration files for testing with automatic
  cleanup'
author: 'dchimento'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: shield
  color: red

# Define your inputs here.
inputs:
  fireblocks-secret:
    description: 'Fireblocks secret key content (PEM format)'
    required: true
  fireblocks-api-key:
    description: 'Fireblocks API key'
    required: true
  fireblocks-vault:
    description: 'Fireblocks vault ID'
    required: false
    default: '0'
  fireblocks-endpoint:
    description: 'Fireblocks API endpoint URL'
    required: false
    default: 'https://sandbox-api.fireblocks.io'
  solana-rpc-url:
    description: 'Solana RPC URL'
    required: false
    default: 'https://api.devnet.solana.com'
  commitment:
    description: 'Solana commitment level'
    required: false
    default: 'finalized'
  poll-timeout:
    description: 'poll timeout in milliseconds'
    required: false
    default: '90'
  poll-interval:
    description: 'poll timeout in milliseconds'
    required: false
    default: '90'

# Define your outputs here.
outputs:
  solana-config-path:
    description: 'solana cli config'
  fireblocks-config-path:
    description: 'fireblocks signer config'

runs:
  using: node20
  main: dist/index.js
  post: dist/post.js
